# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# On garde quand même la configuration pour le Kernel (au cas où)
kernel:
    resource: App\Kernel
    type: attribute